### PR TITLE
New puzzle

### PR DESCRIPTION
**Pull request by Eroldin**

### CODE REVIEW

**Comment by Eroldin** [comment]
Solution:
https://www.youtube.com/watch?v=76FoRXFGD_U

**Comment by Gideon9212** [comment]
If you have time to record a solution on youtube, you have time to upload the solution via a reply file correctly. Will not approve until reply file is sent.

**Comment by Eroldin** [comment]
My apologies, I forgot that file reply was an option. Here yo go:
[Puzzle 10 Solution.zip](https://github.com/ProjectIgnis/Puzzles/files/14195980/Puzzle.10.Solution.zip)

**Comment by Gideon9212** [comment]
...Going to stress again to upload the solution via **reply** file correctly as per readme. A MP4 of a puzzle is not the correct format requested.

**Comment by Gideon9212** [comment]
Will close this in a week from now if a replay file isn't sent correctly. Remember to after you solve the puzzle, save the replay then upload it here is what I'm asking.

**Pull request closed without merging**
