### PR TITLE
Added New Puzzle

### PR DESCRIPTION
**Pull request by banyspy**
Added new puzzles to the 'Miscellaneous' folder.
Banyspy_03_Absolute_Defense.lua
A puzzle that consist of multiple layer of defense mechanism that player has to figure how to breakthrough and OTK.

Solution:  [Absolute Defense Solution.zip](https://github.com/ProjectIgnis/Puzzles/files/12447844/Absolute.Defense.Solution.zip)

### CODE REVIEW

**Comment by banyspy** [comment]
Actually, there's something I want to change in puzzle. It doesn't affect the solution, but rather fix some loophole.

So don't merge yet, I will update later.

**Comment by Gideon9212** [comment]
If there is cards changed around in any manner, need to upload a new solution unless it's a very minor change.
I have not had time to check this pull yet but I'm just stating this now that when you change it, please consider uploading a new solution in a comment.

**Comment by banyspy** [comment]
I have already update it. It's ready to be merged now.

> It doesn't affect the solution, but rather fix some loophole.

I end up change it a lot. Significantly different from before.
So here's new solution:  [Absolute_Defense_Solution.zip](https://github.com/ProjectIgnis/Puzzles/files/12453234/Absolute_Defense_Solution.zip)

**Comment by Gideon9212** [comment]
Everything looks good.

**Comment by yybbwc** [comment]
> I have already update it. It's ready to be merged now.
> 
> > It doesn't affect the solution, but rather fix some loophole.
> 
> I end up change it a lot. Significantly different from before.
> So here's new solution:  [Absolute_Defense_Solution.zip](https://github.com/ProjectIgnis/Puzzles/files/12453234/Absolute_Defense_Solution.zip)

I finished 59,000 life points, so you can continue to improve the puzzle.

**Pull request merged**
