### PR TITLE
Added new puzzles

### PR DESCRIPTION
**Pull request by Eroldin**
I've created two new puzzles.

### CODE REVIEW

**Comment by Eroldin** [comment]
Puzzle 10
1. Summon Burstinatrix
2. Order to Charge --> Magma Neos
3. Mind Control --> Avian
5. O - Oversoul
6. Dark Fusion
7. Pot of greed. Draw 1 extra
8. Dimensional Fissure
9. Ritual of Grace. Tribute Caam, Serenity of Gusto & Amazoness Paladin
10. Select Shorus of Sanctuary with Northwemko's Effect
11. Pot of Grred. Draw 1 extra
12. Graceful Charity. Discard Salamandra & Wynn the Wind Charmer
13. Dimmension Fusion
14. Amazoness Spellcaster --> Destiny End Dragoon
15. De-Spell --> Dimensional Fissure
16. Pot of Greed. Draw 1 extra
17. Fighting Spirit --> Northwemko
18. Special Summon Familiar-Possessed - Wynn from deck
19. Premature Burial --> Caam
20. Gift of the Martyr --> Caam --> Wynn
21. Fusion Weapon
22. Elegant Egotist
---Battle Phase---
23. Northwemko --> Dragoon
24. Cyber Harpie Lady --> Spirit of the Pot of Greed
25. Wynn --> Neos
26. Inferno Wing --> Spirit
27. Attack with Paladin for the Win


Puzzle 11
1. Return from the Different Dimension
2. Order to Smash --> Mokey Mokey --> Sword of Revealing Light x2
3. Pot of Benevolence --> Mokey & Swords
4. Advanced Ritual Art
5. Relinquished --> Guardian Sphinx
6. Pot of Greed
7. Polymerization
8. Thousand-Eye Restrict --> Guardian Sphinx
9. De-Fusion. Do summon
10. Relinquished --> Sphinx Teleia
11. Shrink --> Relinquished
12. Mist Body --> Relinquished
11. Axe of Despair --> Theinen the Great Sphinx
12. Twin Swords of Flashing Light - Tryce --> Relinquished
---Battle Phase---
13. Attack Theinen twice with Relinquished for the win

**Comment by NaimSantos** [comment]
You can put the solution as a comment in the puzzle file so it is available to anyone that needs to consult it later.

**Comment by Eroldin** [comment]
@NaimSantos I will consider it. My issue with adding the solution to the puzzle is that people can choose to read the answer before they even try to solve it.

**Comment by Eroldin** [comment]
@NaimSantos although I'm not totally happy with it, the answers have been added to the puzzles.

**Comment by NaimSantos** [comment]
There is nothing to be happy or unhappy about it. By having the solution written in puzzle file, you save some trouble with people who are unable to solve it and cannot find the solution anywhere else. Every now and then we have someone asking for the solutions of old puzzles, and frequently those are left unanswered. Writting down the solutions was something I started doing some time ago, but never uploaded then. And it was just a suggestion for you because you had it already written in your initial message. It was not an imposition.

image


Regarding your initial message:
> My issue with adding the solution to the puzzle is that people can choose to read the answer before they even try to solve it.

A regular user will not think that the solution is contained within the file itself because they are not going to open and edit that file. The coments are also not shown in the preview `message` block. And if a user does figure out that the solution is within the file and just repeat the steps without even trying to solve it first, they aren't really interested in the puzzle itself.

**Comment by Eroldin** [comment]
@NaimSantos You make some excellent points.

**Comment by Gideon9212** [comment]
@Eroldin Will close this in a few days if no changes are made.

**Comment by RayRJJackson** [comment]
> @Eroldin Will close this in a few days if no changes are made.

He did change them, in fact. I checked the files and they had the answer in them.

**Comment by Gideon9212** [comment]
I am blind

**Pull request merged**
