### PR TITLE
Create RashFaustinho_06_Rex_VS_Yusei

### PR DESCRIPTION
**Pull request by RashFaustinho**
Simple puzzle meant to showcase Rex Goodwin's "combo"

Should be very easy, did this just for fun because these effects are kinda nuts and almost impossible to pull off

YRPX:

[Rex Goodwin VS Yusei.zip](https://github.com/user-attachments/files/15754275/Rex.Goodwin.VS.Yusei.zip)

### CODE REVIEW

**Comment by RayRJJackson** [comment]
Maybe add the written solution to the puzzle file? I saw puzzles getting approved by adding that.

**Review by RayRJJackson — CHANGES_REQUESTED** [review]
Add the solution at the bottom like so:

`--[[Solution:  
1-  
2-  
3-
--]]`
Like so and you could get approved faster.

**Comment by RayRJJackson** [comment]
@NaimSantos Can you add it? The author added the solution.

**Comment by Gideon9212** [comment]
@RayRJJackson New puzzles to be added is my department. I got it

**Comment by RayRJJackson** [comment]
> @RayRJJackson New puzzles to be added is my department. I got it

@Gideon9212 Oh okay, tagged Naim because last time he merged a couple of my pull requests. Or was it because they were edits of pre-existing ones?

**Comment by Gideon9212** [comment]
Edits of pre-existing ones don't need my approval. View the readme for this repo.

**Pull request merged**
