### PR TITLE
Added new puzzles.

### PR DESCRIPTION
**Pull request by FurtieHubo**
Added new puzzles to the 'Miscellaneous' folder. Removed the hall of fame system. If you doubt that the puzzles are not beatable, feel free to contact me.

### CODE REVIEW

**Comment by FurtieHubo** [comment]
Added the following puzzles:

- Dark Synchro (Crazy Level Eater combos)
- D/D/D (An advanced D/D/D Combo)
- Gallis FTK (Yet another one card Gallis FTK)
- Infernity (A combination of Synchro & XYZ Infernity)
- Inzektor (Butterfly Dagger - Elma & Inzektor Dragonfly provides so much advantage)
- Kozmo (Fire King Island Kozmo Combos)
- Slash Draw FTK (Yet another Slash Draw FTK)
- Sophia (One Card Combo to summon Sophia)
- True Metalfoes Kozmo (A crazy combination of archetypes)
- Zefra (A crazy combo to showcase to strength of MR3 Pendulumsummon)

I hope you appreciate the variety.

**Comment by FurtieHubo** [comment]
In addition, I also added a Mr. 4 Spyral Puzzle.

**Comment by FurtieHubo** [comment]
Renamed the puzzles to fit the naming conventions.

**Comment by Gideon9212** [comment]
No issues. Puzzles beatable. Merging.

**Pull request merged**
