### PR TITLE
Puzzles made by Eroldin

### PR DESCRIPTION
**Pull request by Eroldin**
Removed the license. It's fine to be released under the AGPL license.
I will send the solutions via reply.

### CODE REVIEW

**Comment by Eroldin** [comment]
[solutions.zip](https://github.com/ProjectIgnis/Puzzles/files/5277437/solutions.zip)

**Comment by Gideon9212** [comment]
Correct submitting this time. Great! 

Only one tiny nitpick, we rate complexity/difficulty by number between 1-10, not stars. You can edit the current pull with that change. 

Soon that change is done and I get the time to check the solutions, and found to be correct, it should be ok for a merge.

**Review by Eroldin — COMMENTED** [review]
Rating has been changed according to my understanding of difficulty.

**Comment by Gideon9212** [comment]
Looks good. Merging.

**Pull request merged**
