### PR TITLE
Add puzzles from rush duel game

### PR DESCRIPTION
**Pull request by edo9300**
Those puzzles were automatically parsed from the rush duel switch game, the numbers don't match 1:1 with the puzzle indexes in game, so some might actually be unused in the game. They have not been tested but should work.

Things to handle properly:

- [x] Maximum monsters

### CODE REVIEW

**Comment by Gideon9212** [comment]
- [ ] Puzzle 1 Solution

- [ ] Puzzle 2 Solution

- [ ] Puzzle 3 Solution

- [ ] Puzzle 4 Solution

- [ ] Puzzle 5 Solution

- [ ] Puzzle 6 Solution

- [ ] Puzzle 7 Solution

- [ ] Puzzle 8 Solution

- [ ] Puzzle 9 Solution

- [ ] Puzzle 10 Solution

- [ ] Puzzle 11 Solution

- [ ] Puzzle 12 Solution

- [ ] Puzzle 13 Solution

- [ ] Puzzle 14 Solution

- [ ] Puzzle 15 Solution

- [ ] Puzzle 16 Solution

- [ ] Puzzle 17 Solution

- [ ] Puzzle 18 Solution

- [ ] Puzzle 19 Solution

- [ ] Puzzle 20 Solution

- [ ] Puzzle 21 Solution

- [ ] Puzzle 22 Solution

- [ ] Puzzle 23 Solution

- [ ] Puzzle 24 Solution

- [ ] Puzzle 25 Solution

- [ ] Puzzle 26 Solution

- [ ] Puzzle 27 Solution

- [ ] Puzzle 28 Solution

- [ ] Puzzle 29 Solution

- [ ] Puzzle 30 Solution

- [ ] Puzzle 31 Solution

- [ ] Puzzle 32 Solution

- [ ] Puzzle 33 Solution

- [ ] Puzzle 34 Solution

- [ ] Puzzle 35 Solution

- [ ] Puzzle 36 Solution

- [ ] Puzzle 37 Solution

- [ ] Puzzle 38 Solution

- [ ] Puzzle 39 Solution

- [ ] Puzzle 40 Solution

- [ ] Puzzle 41 Solution

- [ ] Puzzle 42 Solution

- [ ] Puzzle 43 Solution

- [ ] Puzzle 44 Solution

- [ ] Puzzle 45 Solution

- [ ] Puzzle 46 Solution

- [ ] Puzzle 47 Solution

- [ ] Puzzle 48 Solution

- [ ] Puzzle 49 Solution

- [ ] Puzzle 50 Solution

- [ ] Puzzle 51 Solution

- [ ] Puzzle 52 Solution

- [ ] Puzzle 53 Solution

- [ ] Puzzle 54 Solution

- [ ] Puzzle 55 Solution

- [ ] Puzzle 56 Solution

- [ ] Puzzle 57 Solution

- [ ] Puzzle 58 Solution

- [ ] Puzzle 59 Solution

- [ ] Puzzle 60 Solution

- [ ] Puzzle 61 Solution

- [ ] Puzzle 62 Solution

- [ ] Puzzle 63 Solution

- [ ] Puzzle 64 Solution

- [ ] Puzzle 65 Solution

- [ ] Puzzle 66 Solution

- [ ] Puzzle 67 Solution

- [ ] Puzzle 68 Solution

- [ ] Puzzle 69 Solution

- [ ] Puzzle 70 Solution

- [ ] Puzzle 71 Solution

- [ ] Puzzle 72 Solution

- [ ] Puzzle 73 Solution

- [ ] Puzzle 74 Solution

- [ ] Puzzle 75 Solution

- [ ] Puzzle 76 Solution

- [ ] Puzzle 77 Solution

- [ ] Puzzle 78 Solution

- [ ] Puzzle 79 Solution

- [ ] Puzzle 80 Solution

- [ ] Puzzle 81 Solution

- [ ] Puzzle 82 Solution

- [ ] Puzzle 83 Solution

- [ ] Puzzle 84 Solution

- [ ] Puzzle 85 Solution

- [ ] Puzzle 86 Solution

- [ ] Puzzle 87 Solution

- [ ] Puzzle 88 Solution

- [ ] Puzzle 89 Solution

- [ ] Puzzle 90 Solution

- [ ] Puzzle 91 Solution

- [ ] Puzzle 92 Solution

- [ ] Puzzle 93 Solution

- [ ] Puzzle 94 Solution

- [ ] Puzzle 95 Solution

- [ ] Puzzle 96 Solution

- [ ] Puzzle 97 Solution

- [ ] Puzzle 98 Solution

- [ ] Puzzle 99 Solution

- [ ] Puzzle 100 Solution

- [ ] Puzzle 101 Solution

- [ ] Puzzle 102 Solution

- [ ] Puzzle 103 Solution

- [ ] Puzzle 104 Solution

- [ ] Puzzle 105 Solution

- [ ] Puzzle 106 Solution

- [ ] Puzzle 107 Solution

- [ ] Puzzle 108 Solution

- [ ] Puzzle 109 Solution

- [ ] Puzzle 110 Solution

- [ ] Puzzle 111 Solution

- [ ] Puzzle 112 Solution

- [ ] Puzzle 113 Solution

- [ ] Puzzle 114 Solution

- [ ] Puzzle 115 Solution

- [ ] Puzzle 116 Solution

- [ ] Puzzle 117 Solution

- [ ] Puzzle 118 Solution

- [ ] Puzzle 119 Solution

- [ ] Puzzle 120 Solution

- [ ] Puzzle 121 Solution

- [ ] Puzzle 122 Solution

- [ ] Puzzle 123 Solution

- [ ] Puzzle 124 Solution

- [ ] Puzzle 125 Solution

- [ ] Puzzle 126 Solution

- [ ] Puzzle 127 Solution

- [ ] Puzzle 128 Solution

- [ ] Puzzle 129 Solution

- [ ] Puzzle 130 Solution

- [ ] Puzzle 131 Solution

- [ ] Puzzle 132 Solution

- [ ] Puzzle 133 Solution

- [ ] Puzzle 134 Solution

- [ ] Puzzle 135 Solution

- [ ] Puzzle 136 Solution

- [ ] Puzzle 137 Solution

- [ ] Puzzle 138 Solution

- [ ] Puzzle 139 Solution

- [ ] Puzzle 140 Solution

- [ ] Puzzle 141 Solution

- [ ] Puzzle 142 Solution

- [ ] Puzzle 143 Solution

- [ ] Puzzle 144 Solution

- [ ] Puzzle 145 Solution

- [ ] Puzzle 146 Solution

- [ ] Puzzle 147 Solution

- [ ] Puzzle 148 Solution

- [ ] Puzzle 149 Solution

- [ ] Puzzle 150 Solution

- [ ] Puzzle 151 Solution

- [ ] Puzzle 152 Solution

- [ ] Puzzle 153 Solution

- [ ] Puzzle 154 Solution

- [ ] Puzzle 155 Solution

- [ ] Puzzle 156 Solution

- [ ] Puzzle 157 Solution

- [ ] Puzzle 158 Solution

- [ ] Puzzle 159 Solution

- [ ] Puzzle 160 Solution

- [ ] Puzzle 161 Solution

- [ ] Puzzle 162 Solution

- [ ] Puzzle 163 Solution

- [ ] Puzzle 164 Solution

- [ ] Puzzle 165 Solution

- [ ] Puzzle 166 Solution

- [ ] Puzzle 167 Solution

- [ ] Puzzle 168 Solution
- [ ] Puzzle 169 Solution

- [ ] Puzzle 170 Solution

- [ ] Puzzle 171 Solution

- [ ] Puzzle 172 Solution

- [ ] Puzzle 173 Solution

- [ ] Puzzle 174 Solution

- [ ] Puzzle 175 Solution

- [ ] Puzzle 176 Solution

- [ ] Puzzle 177 Solution

- [ ] Puzzle 178 Solution

- [ ] Puzzle 179 Solution

- [ ] Puzzle 180 Solution

- [ ] Puzzle 181 Solution

- [ ] Puzzle 182 Solution

- [ ] Puzzle 183 Solution

- [ ] Puzzle 184 Solution

- [ ] Puzzle 185 Solution

- [ ] Puzzle 186 Solution

- [ ] Puzzle 187 Solution

- [ ] Puzzle 188 Solution

- [ ] Puzzle 189 Solution

- [ ] Puzzle 190 Solution

- [ ] Puzzle 191 Solution

- [ ] Puzzle 192 Solution

- [ ] Puzzle 193 Solution
- [ ] Puzzle 194 Solution

- [ ] Puzzle 195 Solution

- [ ] Puzzle 196 Solution

- [ ] Puzzle 197 Solution

- [ ] Puzzle 198 Solution

- [ ] Puzzle 199 Solution

- [ ] Puzzle 200 Solution

- [ ] Puzzle 201 Solution

- [ ] Puzzle 202 Solution

- [ ] Puzzle 203 Solution

- [ ] Puzzle 204 Solution

- [ ] Puzzle 205 Solution

- [ ] Puzzle 206 Solution

- [ ] Puzzle 207 Solution

- [ ] Puzzle 208 Solution

- [ ] Puzzle 209 Solution

- [ ] Puzzle 210 Solution

- [ ] Puzzle 211 Solution

**Comment by edo9300** [comment]
"Mappings" from internal id to ids shown in game
```1) Blue-Eyes White Dragon:
    1 -> 1
    [...]
    12 -> 12
    13 -> 14
    [...]
    20 -> 21

2) Magician Puzzles:
    1 -> 22
    [...]
    15 -> 36
    16 -> 39
    [...]
    21 -> 44

3) SHIELD AND SWORD:
    1 -> 45
    [...]
    15 -> 59

4) MIRAGIAS:
    1 -> 60
    [...]
    19 -> 78

5) Super Magitek Deity Magnum Over Road:
    1 -> 79
    [...]
    14 -> 92

6) Build Dragon the Mythic Sword Dragon:
    1 -> 93
    [...]
    21 -> 113

8) YGGDRASSIL:
    1 -> 125
    [...]
    5 -> 129
    6 -> 131
    7 -> 132

9) Wurm Ex-Cavator:
    1 -> 133
    [...]
    7 -> 139

10) CAN-RE:D DUEL PUZZLE!:
    1 -> 140
    [...]
    27 -> 166

11) Supreme flagship magnum overlord:
    1 -> 167
    [...]
    11 -> 177

12) Something:
    1 -> 178
    [...]
    20 -> 197

13) Something else:
    1 -> 198
    [...]
    20 -> 217
```


Puzzles number 13, 37, 38, 130 are puzzles not available in game via the puzzle menu (they might be available in other parts of the game), if they are considered solvable they can be added. (Puzzle 38 is not solvable)

**Comment by Gideon9212** [comment]
Puzzle 37 is invalid and needs del from this pull

**Comment by Gideon9212** [comment]
Special thanks to Terranigmahack for helping on the puzzle solutions. 
This is also a reminder to @edo9300 to remove puzzle 37.

**Comment by Gideon9212** [comment]
Puzzle 13 updated with new solution to match new changes.

**Comment by Gideon9212** [comment]
The pull matches the requirements now. Double checking with @edo9300 to confirm this is the final changes before merging.

Other wise this is greenlighted and good to go. 👍

**Pull request merged**
